### ISSUE TITLE
can you share venus repository used during mosh git course ? If you have that repository please share. 

### ISSUE THREAD

**Issue by sachinwalunjakar** [jmschp/mosh-ultimate-git-course#1]

**Comment by jmschp** [comment]
No, I don1t have it.

**Comment by jmschp** [comment]
No, I don1t have it.

**Comment by saadelkenawy** [comment]
yes , i have this file 
[Venus.zip](https://github.com/jmschp/mosh-ultimate-git-course/files/8807205/Venus.zip)

**Comment by metirepo** [comment]
> yes , i have this file [Venus.zip](https://github.com/jmschp/mosh-ultimate-git-course/files/8807205/Venus.zip)

thanks

**Comment by Amirkolo** [comment]
> yes , i have this file [Venus.zip](https://github.com/jmschp/mosh-ultimate-git-course/files/8807205/Venus.zip)

thanks boss

**Comment by BobbaruK** [comment]
> yes , i have this file [Venus.zip](https://github.com/jmschp/mosh-ultimate-git-course/files/8807205/Venus.zip)

Do you have Mercury zip too? @saadelkenawy
