### ISSUE TITLE
The Ultimate GIT Course with Mosh hamadani / Venus Repo

### ISSUE THREAD

**Issue by saadelkenawy** [jmschp/mosh-ultimate-git-course#2]
shared :)
enjoy 
[Venus.zip](https://github.com/jmschp/mosh-ultimate-git-course/files/8807213/Venus.zip)

**Comment by jmschp** [comment]
@saadelkenawy 

I'm sorry, but I don't think we should be publicly sharing this.
Mosh courses are private and paid.

**Comment by saadelkenawy** [comment]
> @saadelkenawy 
> 
> 
> 
> I'm sorry, but I don't think we should be publicly sharing this.
> 
> Mosh courses are private and paid.
> 
> 

Am sorry too but i am  not sharing the course am sharing just files oy own file it' related to mosh
