### ISSUE TITLE
UI Fixes issue

### ISSUE THREAD

**Issue by justankiit** [jmschp/mosh-ultimate-git-course#3]
On the bottom (Footer) of the Webpage ,Where is some  text has been written ,it should be in Black Color and the Social icons need Some margin and padding.

![image](https://user-images.githubusercontent.com/111564362/233837136-4e14f3c5-8f65-4cb9-a439-c052dced92a2.png)

**Comment by jmschp** [comment]
Hi @kumarankit999 

I guess you miss understood something.

My repo does not have anything to do with Code With Mosh web page.
